[package]
name = "hit"
version = "1.3.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
configparser = "3.1.0"
flate2 = "1.1.1"
hex = "0.4.3"
hf = "0.4.0"
home = "0.5.11"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha1 = "0.10.6"
