[package]
name = "hit"
version = "0.10.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
flate2 = "1.1.1"
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha1 = "0.10.6"
